/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meuProjetoJava;

public class App {

    public static void main(String[] args) {
        /*
        String nome = "Amanda";
        int idade = 15;
        double altura = 1.60;
        boolean seiJava = true;
        char letraInicial = 'A';

        int num1 = 1;
        int num2 = 2;

        double nota1 = 9.5;
        double nota2 = 9.9;
        double nota3 = 10;

        int par1 = 2;
        int restoPar = (par1 % 2);

        System.out.println("Nome: " + nome + "\r\nIdade: " + idade + "\r\nAltura: " + altura);

        System.out.println("Soma: " + (num1 + num2));

        System.out.println("Media: " + ((nota1 + nota2 + nota3) / 3));

        if (restoPar == 0) {
            System.out.println("Par\r\n");
        } else {
            System.out.println("Impar\r\n");
        }
        */
        
        /*
        int numero = 4;
        
        if (numero > 0) {
            System.out.println(numero + " é positivo");
        } else if (numero == 0) {
            System.out.println(numero + " é igual a zero");
        } else if (numero < 0) {
            System.out.println(numero + " é negativo");
        } else {
            System.out.println(numero + " talvez não seja um número");
        }
        */
        /*
        int variavel = 5;
        
        switch (variavel) {
            case 1:
                System.out.println("Domingo");
                break;
            case 2:
                System.out.println("Segunda");
                break;
            case 3:
                System.out.println("Terça");
                break;
            case 4:
                System.out.println("Quarta");
                break;
            case 5:
                System.out.println("Quinta");
                break;
            case 6:
                System.out.println("Sexta");
                break;
            case 7:
                System.out.println("Sábado");
                break;
            default:
            System.out.println("Resultado não encontrado");
        }
        */
        /*
        int numero = 2;
        // tipo variavel (condição) ? valor_se_vdd : valor_se_falso;
        String resultado = (numero % 2 ==0) ? "par" : "ímpar";
                System.out.println("Este numero eh " + resultado);
        
        int numeroPN = 2;
        // tipo variavel (condição) ? valor_se_vdd : valor_se_falso;
        String resultado1 = (numeroPN > 0) ? "positivo" : "negativo";
                System.out.println("Este numero eh " + resultado1);
        
        int idade = 18;
        // tipo variavel (condição) ? valor_se_vdd : valor_se_falso;
        String resultado2 = (idade >= 18) ? "maior de idade" : "menor de idade";
                System.out.println("Voce eh " + resultado2);
        
        int num1 = 2;
        int num2 = 3;
        
        String resultado3 = (num1 > num2) ? "maior" : "menor";
                System.out.println(num1 + " eh "+ resultado3);
        
        int ano = 2000;
        
        String resultado4 = (ano % 4 == 0 || (ano % 100 != 0 && ano % 400 == 0)) ? "bissexto": "nao-bissexto";
                System.out.println(ano + " eh "+ resultado4);
        */
    }
}
