/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Arrays;

public class App {
    public static void main(String[] args) {
      /*
        int [] numeros;
        numeros = new int[5];
        
        int [] numeros02 = {1, 2, 3, 4, 5};
        
        System.out.println(numeros02[0]);
        System.out.println(numeros02[5]);
        
        for (int numero : numeros02) {
            System.out.println(numero);
        }
        */
      /*
        String [] nomes = {"amanda", "dani", "paulo", "jeferson", "taylor"};
        
        nomes[2] = "jobiscléison";
        for(String nome : nomes) {
            System.out.println(nome);
        }
        */
    }
}
