/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meuProjetoJava;

public class App {

    public static void main(String[] args) {
        String nome = "Amanda";
        int idade = 15;
        double altura = 1.60;
        boolean seiJava = true;
        char letraInicial = 'A';
        
        int num1 = 1;
        int num2 = 2;
        
        double nota1 = 9.5;
        double nota2 = 9.9;
        double nota3 = 10;
        
        int par1 = 2;
        
        System.out.println("Nome: " + nome + "\r\nIdade: " + idade + "\r\nAltura: " + altura);
        
        System.out.println("Soma: " + (num1 + num2));
        
        System.out.println("Media: " + ((nota1 + nota2 + nota3)/3));
        
        System.out.println("Se par, resultado: 0 \r\n" + (par1 % 2));
    }
}